### ISSUE TITLE
Problem with parsing prefixed keyframes

### ISSUE THREAD

**Issue by peterbe** [aymerick/douceur#4]
With this CSS 

``` css
@-webkit-keyframes segment-spin {
  from {
    -webkit-transform: rotate(0deg);
    transform: rotate(0deg)
  }
  to {
    -webkit-transform: rotate(360deg);
    transform: rotate(360deg)
  }
}
```

I get:

```
Unexpected } character: CHAR (line: 11, column: 1): "}"
```

I think it's because it's not a recognized "AtRule". This works just fine to parse:

```
@keyframes segment-spin{
from{-webkit-transform:rotate(0deg);transform:rotate(0deg)}
  to{-webkit-transform:rotate(360deg);transform:rotate(360deg)}
}
```

Vendor prefixes makes me cry at night, but a possible solution would be to extend 
[this line](https://github.com/aymerick/douceur/blob/7176f146738114e7386d4f915a0bbf55945e22c9/css/rule.go#L23).

But pardon me, why maintain a list like that? What other strings that starts with a `@` can't all be considered "at rules"? E.g [this function](https://github.com/aymerick/douceur/blob/7176f146738114e7386d4f915a0bbf55945e22c9/css/rule.go#L69) could be something like:

``` go
func (rule *Rule) EmbedsRules() bool {
    return strings.HasPrefix(rule.Name, "@")
}
```

No?
